# Generated by Django 2.2.7 on 2020-03-22 19:59

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='test/', validators=[utils.validators.validate_image_dimension], verbose_name='Image')),
            ],
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
